# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: steamStorageOptimiser
            asset_name: steamStorageOptimiser-linux
          - os: windows-latest
            artifact_name: steamStorageOptimiser.exe
            asset_name: steamStorageOptimiser-windows
          - os: macos-latest
            artifact_name: steamStorageOptimiser
            asset_name: steamStorageOptimiser-macos
            
    steps:
    - uses: actions/checkout@v2
    - name: Install Requirements
      run: pip install -r src/requirements.txt pyinstaller
    - name: Build Release
      run: pyinstaller -F src/steamStorageOptimiser.py
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/steamStorageOptimiser/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }} 
#   build-releases:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

#     steps:
#     - name: Get latest release
#       id: latest_release_info
#       uses: jossef/action-latest-release-info@v1.1.0
#     - uses: actions/checkout@v2
#     - uses: actions/setup-python@v2
#       with:
#         python-version: 3.7

#     - run: pip install -r src/requirements.txt pyinstaller
#     - run: pyinstaller -F src/steamStorageOptimiser.py
#     # Optionally verify that it works (provided that it does not need user interaction)
#     - ./dist/your-code/your-code
#     - uses: actions/upload-artifact@v2
#       with:
#         path: dist/*
#     - run: ls -R
#     - uses: xresloader/upload-to-github-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         file: "dist/*"
#         tags: false
#         draft: false
#         update_latest_release: true
#     - uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_name: steamStorageOptimiser.exe
#         asset_path: src/dist/*
#         asset_content_type: application/octet-stream
#     - name: Upload binary to release
#       uses: svenstaro/upload-release-action@v2
#       with:
#         repo_token: ${{ secrets.GITHUB_TOKEN }}
#         file: dist/*
#         file_glob: true
#         asset_name: mything
#         tag: ${{ github.ref }}
#         overwrite: true
#         body: "This is my release text"
#     - uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.PAT }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_name: steamStorageOptimiser-linux
#         asset_path: src/dist/linux/steamStorageOptimiser
#         asset_content_type: application/octet-stream

