name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: steamStorageOptimiser
            asset_name: steamStorageOptimiser-linux
          - os: windows-latest
            artifact_name: steamStorageOptimiser.exe
            asset_name: steamStorageOptimiser-windows
          - os: macos-latest
            artifact_name: steamStorageOptimiser
            asset_name: steamStorageOptimiser-macos
            
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Requirements
      run: pip install -r src/requirements.txt pyinstaller
    - name: Build Release
      run: pyinstaller -F src/steamStorageOptimiser.py
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.run_number }}

