name: Python application

on: push

permissions:
  contents: write
  
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: steamStorageOptimiser-linux
          - os: windows-latest
            artifact_name: steamStorageOptimiser-win.exe
          - os: macos-latest
            artifact_name: steamStorageOptimiser-mac
            
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Requirements
      run: pip install -r src/requirements.txt pyinstaller
    - name: Build Release
      run: pyinstaller --onefile --console src/steamStorageOptimiser.py --name ${{ matrix.artifact_name }}
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        commitMode: "true" #Remove when moving to using PRs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./dist/${{ matrix.artifact_name }}
        body: ${{steps.github_release.outputs.changelog}}
