name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: steamStorageOptimiser
            asset_name: steamStorageOptimiser-linux
          - os: windows-latest
            artifact_name: steamStorageOptimiser.exe
            asset_name: steamStorageOptimiser-windows.exe
          - os: macos-latest
            artifact_name: steamStorageOptimiser.app
            asset_name: steamStorageOptimiser-macos.app
            
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Requirements
      run: pip install -r src/requirements.txt pyinstaller
    - name: Build Release
      run: pyinstaller -F --windowed src/steamStorageOptimiser.py
    - run: ls -R
    - name: Upload binaries to release
      uses: actions/upload-artifact@v3
      with:
        path: ./dist/${{ matrix.artifact_name }}
        name: ${{ matrix.asset_name }}
